CREATE DATABASE DESAFIO_PLUFT;

USE DESAFIO_PLUFT;

CREATE TABLE LOGRADOUROS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,RUA VARCHAR(250) NOT NULL
	,CEP CHAR(8) NOT NULL
	,BAIRRO VARCHAR(250) NOT NULL
	,MUNICIPIO VARCHAR(100) NOT NULL
	,ESTADO VARCHAR(100) NOT NULL
);

CREATE TABLE AREAS_ATIVIDADE (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE CAPACIDADES (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,DESCRICAO TEXT NOT NULL
	,QUANTIDADE CHAR(30)
);

CREATE TABLE STATUS_AGENDAMENTO (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME VARCHAR(100) NOT NULL
);

CREATE TABLE VALORES (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,VALOR CHAR(8)
);

CREATE TABLE SERVICOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME_SERVICO VARCHAR(250) NOT NULL
	,DESCRICAO TEXT NOT NULL
	,ID_VALORES INT NOT NULL FOREIGN KEY REFERENCES VALORES(ID)
	,ID_CAPACIDADES INT NOT NULL FOREIGN KEY REFERENCES CAPACIDADES(ID)
);


CREATE TABLE INSTITUICOES (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME_FANTASIA VARCHAR(250) NOT NULL
	,RAZAO_SOCIAL VARCHAR(250) NOT NULL
	,CNPJ CHAR(14) UNIQUE NOT NULL
	,TELEFONE CHAR(11) NOT NULL
	,ID_AREAS_ATIVIDADE INT NOT NULL FOREIGN KEY REFERENCES AREAS_ATIVIDADE(ID)
	,ID_LOGRADOURO INT NOT NULL FOREIGN KEY REFERENCES LOGRADOUROS (ID)
);

CREATE TABLE TIPO_USUARIOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME VARCHAR(250) NOT NULL
	,RG CHAR(10) UNIQUE NOT NULL
	,CPF CHAR(11) UNIQUE NOT NULL
	,EMAIL VARCHAR(250) UNIQUE NOT NULL
	,SENHA VARCHAR(250) NOT NULL
	,TELEFONE CHAR(11) NOT NULL
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID)
	,ID_LOGRADOURO INT FOREIGN KEY REFERENCES LOGRADOUROS(ID)
);

CREATE TABLE LOJISTAS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME VARCHAR(250) NOT NULL
	,RG CHAR(10) UNIQUE NOT NULL
	,CPF CHAR(11) UNIQUE NOT NULL
	,EMAIL VARCHAR(250) UNIQUE NOT NULL
	,SENHA VARCHAR(250) NOT NULL
	,TELEFONE CHAR(11) NOT NULL
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID)
	,ID_INSTITUICAO INT FOREIGN KEY REFERENCES INSTITUICOES(ID)
	,ID_LOGRADOURO INT FOREIGN KEY REFERENCES LOGRADOUROS(ID)
);

CREATE TABLE AGENDAMENTOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,DATA_AGENDAMENTO DATE NOT NULL
	,HORA_AGENDAMENTO TIME NOT NULL
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_INSITUICAO INT FOREIGN KEY REFERENCES INSTITUICOES(ID)
	,ID_SERVICO INT NOT NULL FOREIGN KEY REFERENCES SERVICOS(ID)
	,ID_STATUS INT NOT NULL FOREIGN KEY REFERENCES STATUS_AGENDAMENTO(ID)
);








